models/DataDasar.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\data\ArrayDataProvider;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "data_dasar".
 *
 * @property int $id
 * @property int $files
 * @property int $created_at
 * @property int $updated_at
 * @property int $created_by
 * @property int $updated_by
 */
class DataDasar extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rpjm_data_dasar';
    }

    public function behaviors()
    {
       return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
            // 'sluggable' => [
            //     'class' => SluggableBehavior::className(),
            //     'attribute' => 'name',
            //     'slugAttribute' => 'slug',
            // ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['organisasi_id', 'tahun_data', 'urusan_id'], 'required'],
            [['organisasi_id', 'tahun_data', 'urusan_id', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            // [['organisasi_id', 'urusan_id'],'safe'],
            [['file_name'], 'string'],
            [['files'],'file','skipOnEmpty' => true, 'extensions' => 'xlsx, csv, json, geojson'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'organisasi_id' => Yii::t('app', 'Instansi'),
            'urusan_id' => Yii::t('app', 'Urusan'),
            'tahun_data' => Yii::t('app', 'Tahun Data'),
            'files' => Yii::t('app', 'Files'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * {@inheritdoc}
     * @return DataDasarQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DataDasarQuery(get_called_class());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrganisasi()
    {
        return $this->hasOne(RpjmOrganisasi::className(), ['id' => 'organisasi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUrusan()
    {
        return $this->hasOne(RpjmUrusan::className(), ['id' => 'urusan_id']);
    }

    public function getDataRpjm()
    {
        $inputFileName = $this->files;

        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        $reader->setReadDataOnly(true);
        $spreadsheet = $reader->load($inputFileName);
        $spreadsheetMetaData = $spreadsheet->getProperties();
        $data = $spreadsheet->getActiveSheet()->toArray(null,true,true,true);
        $cleanData = $this->cleanDataIndikator($data);
        return $cleanData;
    }

    public function cleanDataIndikator($data=array())
    {
        // unset($data[0]);
        //  && isset($value['F']) && isset($value['H'])
        foreach ($data as $value) {
            if (!empty($value['B']) && !empty($value['C']) && is_numeric($value['D'])) {
                $clean[] = [
                    'indikator' => $value['B'],
                    // 'slug_indikator' => preg_replace('/\s+/', ' ',$value[1]), 
                    // str_replace(" ","-",$value[1]),
                    'satuan' => $value['C'],
                    'rkpd' => $value['D'],
                    'dppa' => $value['F'],
                    'realisasi' => $value['H'],
                ];    
            }
        }
        // Delete First Row
        array_shift($clean);
        return $clean;
    }

    public function getFileAttributeGridView($sheetData='')
    {
        
        $changeKeyArray[] = ['class' => 'yii\grid\SerialColumn'];
        foreach ($sheetData[0] as $key => $value) {
            $changeKeyArray[] = [
                'attribute' => $key,
                'label' => ucwords($key),
            ];
        }

        return $changeKeyArray;
    }


    public function getDataProvider($dataset)
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' => $dataset,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => $this->getFileAttributeGridView($dataset),
            ],
        ]);

        return $dataProvider;
    }
}

controllers/RpjmIndikatorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\DataDasar;
use app\models\DataDasarSearch;
use app\models\RpjmAnalisa;
use app\models\RpjmCapaian;
use app\models\RpjmCapaianSearch;
use app\models\RpjmIndikator;
use app\models\RpjmIndikatorSearch;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * RpjmIndikatorController implements the CRUD actions for RpjmIndikator model.
 */
class RpjmIndikatorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RpjmIndikator models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RpjmIndikatorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['created_at'=>SORT_DESC]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RpjmIndikator model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $modelAnalisa = RpjmAnalisa::find()->where(['indikator_id'=>$id])->one();
        $searchModelCapaian = new RpjmCapaianSearch();
        $dataProviderCapaian = $searchModelCapaian->search(Yii::$app->request->queryParams);
        $dataProviderCapaian->query->where(['indikator_id'=>$id]);
        $dataProviderCapaian->query->orderBy('tahun_data');

        return $this->render('view', [
            'model' => $this->findModel($id),
            'modelAnalisa' => $modelAnalisa,
            'searchModelCapaian' => $searchModelCapaian,
            'dataProviderCapaian' => $dataProviderCapaian,
        ]);
    }

    /**
     * Creates a new RpjmIndikator model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id='')
    {
        $searchModelDataDasar = new DataDasarSearch();
        $dataProviderDataDasar = $searchModelDataDasar->search(Yii::$app->request->queryParams);
        $dataProviderDataDasar->pagination = ['pageSize' => 5];

        $model = new RpjmIndikator();
        $modelCapaian = new RpjmCapaian();
        $modelAnalisa = new RpjmAnalisa();
        
        if (!empty($id)) {
            $detailProviderDataDasar = DataDasar::findOne($id);    
        }else{
            $detailProviderDataDasar = DataDasar::find()->indexBy('id')->one();
            // echo '<pre>';
            // print_r($detailProviderDataDasar);
            // echo '</pre>';
        }        
        
        if (Yii::$app->request->post()) {
            $indikator = RpjmIndikator::find()->where(['indikator'=>Yii::$app->request->post('indikator')])->one();
            // echo '<pre>';
            // print_r(empty($indikator));
            // echo '</pre>';
            if (empty($indikator)) {
                // Insert Data Indikator dan Capaian
                $model->organisasi_id = Yii::$app->request->post('organisasi_id');
                $model->urusan_id = Yii::$app->request->post('urusan_id');
                $model->indikator = Yii::$app->request->post('indikator');
                $model->satuan = Yii::$app->request->post('satuan');
                if ($model->save()) {
                    // Table Capaian && Table Analisa
                    $modelAnalisa->indikator_id = $model->id;
                    $modelCapaian->indikator_id = $model->id;
                    $modelCapaian->tahun_data = Yii::$app->request->post('tahun_data');
                    $modelCapaian->target_rkpd = Yii::$app->request->post('target_rkpd');
                    $modelCapaian->target_dppa = Yii::$app->request->post('target_dppa');
                    $modelCapaian->capaian = Yii::$app->request->post('capaian');
                    if ($modelCapaian->save() && $modelAnalisa->save()) {
                        return $this->redirect(['view', 'id' => $model->id]);    
                    }else{
                        // Error Capaian
                        foreach ($modelCapaian->getErrors() as $errorMsg) {
                            Yii::$app->session->setFlash('error',$errorMsg);   
                        }

                        // Error Analisa
                        foreach ($modelAnalisa->getErrors() as $errorMsg) {
                            Yii::$app->session->setFlash('error',$errorMsg);   
                        }
                        return $this->redirect(Yii::$app->request->referrer);
                    }
                }else{
                    foreach ($model->getErrors() as $errorMsg) {
                        Yii::$app->session->setFlash('error',$errorMsg);   
                    }
                    return $this->redirect(Yii::$app->request->referrer);
                }    
            }else{
                // Update Data Capaian
                // cek berdasar indikator dan tahun data
                $capaian = RpjmCapaian::find()->where([
                    'indikator_id'=> $indikator->id,
                    'tahun_data'=>Yii::$app->request->post('tahun_data')])->one();
                if (empty($capaian)) {
                    // Insert Baru Data Capaian
                    $modelCapaian->indikator_id = $indikator->id;
                    $modelCapaian->tahun_data = Yii::$app->request->post('tahun_data');
                    $modelCapaian->target_rkpd = Yii::$app->request->post('target_rkpd');
                    $modelCapaian->target_dppa = Yii::$app->request->post('target_dppa');
                    $modelCapaian->capaian = Yii::$app->request->post('capaian');
                    if ($modelCapaian->save()) {
                        return $this->redirect(['view', 'id' => $indikator->id]);    
                    }else{
                        foreach ($modelCapaian->getErrors() as $errorMsg) {
                            Yii::$app->session->setFlash('error',$errorMsg);   
                        }
                        return $this->redirect(Yii::$app->request->referrer);
                    }
                }else{
                    // Update data capaian
                    $capaian->tahun_data = Yii::$app->request->post('tahun_data');
                    $capaian->target_rkpd = Yii::$app->request->post('target_rkpd');
                    $capaian->target_dppa = Yii::$app->request->post('target_dppa');
                    $capaian->capaian = Yii::$app->request->post('capaian');
                    if ($capaian->save()) {
                        return $this->redirect(['view', 'id' => $indikator->id]);    
                    }else{
                        foreach ($capaian->getErrors() as $errorMsg) {
                            Yii::$app->session->setFlash('error',$errorMsg);   
                        }
                        return $this->redirect(Yii::$app->request->referrer);
                    }
                }
            }
            
        }

        return $this->render('create', [
            'model' => $model,
            'searchModelDataDasar' => $searchModelDataDasar,
            'dataProviderDataDasar' => $dataProviderDataDasar,
            'detailProviderDataDasar' => $detailProviderDataDasar,
        ]);
    }

    /**
     * Updates an existing RpjmIndikator model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    // public function actionUpdate($id)
    // {
    //     $model = $this->findModel($id);

    //     if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //         return $this->redirect(['view', 'id' => $model->id]);
    //     }

    //     return $this->render('update', [
    //         'model' => $model,
    //     ]);
    // }

    /**
     * Deletes an existing RpjmIndikator model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the RpjmIndikator model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RpjmIndikator the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RpjmIndikator::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/rpjm-indikator/_analisa.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\DataDasar */

$this->title = Yii::t('app', 'Analisa Indikator Capaian');
?>
<div class="analisa-capaian-indikator">

    <div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
        <div class="box-header with-border">
          <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive">
            <?= DetailView::widget([
		        'model' => $modelAnalisa,
		        'attributes' => [
		            'deskriptif',
		            'analisis',
		        ],
		    ]) ?>
        </div>
    </div> 

</div>

views/rpjm-indikator/_chart-capaian.php
<?php 

use dosamigos\chartjs\ChartJs;
use miloschuman\highcharts\Highcharts;
use miloschuman\highcharts\SeriesDataHelper;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Grafik');

?>

<div class="rpjm-capaian-chart">
  <?php 
    $attribute = array_slice(array_keys($dataProviderCapaian->getModels()[0]['attributes']), 3,3);
    foreach ($attribute as $value) {
        $datasets[] = [
          'label' => ucwords(str_replace('_', ' ', $value)),
          'data' => array_column($dataProviderCapaian->getModels(), $value),
          'backgroundColor' => "rgba(".$r= rand(0,255).",".$g= rand(0,255).",".$b= rand(0,255).",".$opacity=0.8.")",
          'borderColor' => "rgba(".$r.",".$g.",".$b.",".$opacity.")",
          'pointBackgroundColor' => "rgba(".$r.",".$g.",".$b.",".$opacity.")",
          'pointBorderColor' => "#fff",
          'pointHoverBackgroundColor' => "#fff",
          'pointHoverBorderColor' => "rgba(".$r.",".$g.",".$b.",".$opacity.")",
        ];
    }

    // echo '<pre>';
    // print_r($attribute);
    // echo '<br>';
    // print_r($series);
    // echo '<pre>';
   ?>

   <div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
        <div class="box-header with-border">
          <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive">
          <?= ChartJs::widget([
            'type' => 'bar',
            // 'options' => [
            //     'height' => 400,
            //     'width' => 400
            // ],
            'data' => [
                'labels' => array_column($dataProviderCapaian->getModels(), 'tahun_data'),
                'datasets' => $datasets,
            ]
        ]); ?>
        </div>
    </div> 

</div>

views/rpjm-indikator/_detail-data-dasar.php
<?php 

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;


 ?>
<div class="data-dasar-view">
    <!-- <?php Pjax::begin(); ?> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <!-- <p>
        <?= Html::a(Yii::t('app', 'Create Data Dasar'), ['create'], ['class' => 'btn btn-success']) ?>
    </p> -->

<div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
    <div class="box-header with-border">
      <h3 class="box-title"><?= Html::encode('Isi File '.$detailProviderDataDasar->file_name.' - Instansi '.$detailProviderDataDasar->organisasi->nama_organisasi.' - Urusan '.$detailProviderDataDasar->urusan->nama_urusan.' - Tahun '.$detailProviderDataDasar->tahun_data) ?></h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body">
    <?= GridView::widget([
        'dataProvider' => $detailProviderDataDasar->getDataProvider($detailProviderDataDasar->getDataRpjm()),
        // 'filterModel' => $searchModelData,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'indikator',
            'satuan',
            'rkpd',
            'dppa',
            'realisasi',
            [
                'label' => 'Tambah Data',
                // 'attribute' => 'updated_by',
                'format' => 'raw',
                'value' => function ($data) use ($detailProviderDataDasar){
                   return Html::a(Yii::t('app', 'Tambah'), ['create'], [
                        'class' => 'btn btn-warning',
                        'data' => [
                            'confirm' => Yii::t('app', 'Tambah Data Indikator...?'),
                            'method' => 'post',
                            'params' => [
                                'organisasi_id' => $detailProviderDataDasar['organisasi_id'],
                                'urusan_id' => $detailProviderDataDasar['urusan_id'],
                                'indikator' => $data['indikator'],
                                'satuan' => $data['satuan'],
                                'tahun_data' => $detailProviderDataDasar['tahun_data'],
                                'target_rkpd' => $data['rkpd'],
                                'target_dppa' => $data['dppa'],
                                'capaian' => $data['realisasi'],
                            ],
                        ],
                    ]);
                    // return Html::a('Tambah',['xxxx', 
                    //     'indikator' => $data['indikator'],
                    //     'satuan' => $data['satuan'],
                    //     'rkpd' => $data['rkpd'],
                    //     'dppa' => $data['dppa'],
                    //     'realisasi' => $data['realisasi'],
                    // ]);
                    // return $data->updatedBy->nama_lengkap;
                },
            ],

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    </div>
</div>
    <!-- <?php Pjax::end(); ?> -->
</div>

views/rpjm-indikator/_detail.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\DataDasar */

$this->title = Yii::t('app', $model->indikator);
?>
<div class="data-dasar-view">
    <div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
        <div class="box-header with-border">
          <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    // 'id',
                    'indikator',
                    'organisasi.nama_organisasi',
                    'urusan.nama_urusan',
                    // 'slug_indikator',
                    'satuan',
                    'created_at:datetime',
                    'updated_at:datetime',
                    [
                        'label' => 'Dibuat Oleh',
                        'attribute' => 'dibuat',
                        // 'value' => 'dibuat.nama_lengkap',
                        'format' => 'raw',
                        'value' => function ($data){
                            // return Html::a($data->file_name,['view', 'id' => $data->id]);
                            return $data->createdBy->nama_lengkap;
                        },
                    ],
                    [
                        'label' => 'Diupdate Oleh',
                        'attribute' => 'diupdate',
                        // 'value' => 'diupdate.nama_lengkap',
                        'format' => 'raw',
                        'value' => function ($data){
                            // return Html::a($data->file_name,['view', 'id' => $data->id]);
                            return $data->updatedBy->nama_lengkap;
                        },
                    ],
                ],
            ]) ?>
        </div>
    </div>     

</div>

views/rpjm-indikator/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RpjmIndikator */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rpjm-indikator-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'organisasi_id')->textInput() ?>

    <?= $form->field($model, 'urusan_id')->textInput() ?>

    <?= $form->field($model, 'indikator')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'slug_indikator')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'satuan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rpjm-indikator/_grid-capaian.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\RpjmCapaianSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Capaian');
?>
<div class="rpjm-capaian-index">

<div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
        <div class="box-header with-border">
          <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive">
            <?= GridView::widget([
                'dataProvider' => $dataProviderCapaian,
                // 'filterModel' => $searchModelCapaian,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    // 'id',
                    // 'indikator.indikator',
                    'tahun_data',
                    'target_rkpd',
                    'target_dppa',
                    'capaian',
                    'created_at:datetime',
                    'updated_at:datetime',
                    // 'created_by',
                    //'updated_by',

                    // ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div> 
    
</div>

views/rpjm-indikator/_grid-data-dasar.php
<?php 

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;


 ?>
<div class="data-dasar-index">
    <!-- <?php Pjax::begin(); ?> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <!-- <p>
        <?= Html::a(Yii::t('app', 'Create Data Dasar'), ['create'], ['class' => 'btn btn-success']) ?>
    </p> -->

<div class="box box-<?php $head = ['warning','info','danger','default','info']; shuffle($head); echo $head[0] ?>">
    <div class="box-header with-border">
      <h3 class="box-title"><?= Html::encode('Data E-Controlling RPJM') ?></h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body table-responsive">
        <?= GridView::widget([
        'dataProvider' => $dataProviderDataDasar,
        'filterModel' => $searchModelDataDasar,
        'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                // 'id',
                [
                    'label' => 'Nama File',
                    'attribute' => 'file_name',
                    'format' => 'raw',
                    'value' => function ($data){
                        return Html::a($data->file_name,['create', 'id' => $data->id]);
                        // return $data->createdBy->nama_lengkap;
                    },
                ],
                // 'organisasi_id',
                [
                    'label' => 'Organisasi',
                    'attribute' => 'nama_organisasi',
                    'value' => 'organisasi.nama_organisasi',
                    // 'format' => 'raw',
                    // 'value' => function ($data){
                    //     return Html::a($data->file_name,['view', 'id' => $data->id]);
                    //     // return $data->createdBy->nama_lengkap;
                    // },
                ],
                // 'urusan_id',
                [
                    'label' => 'Urusan',
                    'attribute' => 'nama_urusan',
                    'value' => 'urusan.nama_urusan',
                    // 'format' => 'raw',
                    // 'value' => function ($data){
                    //     return Html::a($data->file_name,['view', 'id' => $data->id]);
                    //     // return $data->createdBy->nama_lengkap;
                    // },
                ],
                'tahun_data',
                'created_at:datetime',

                // ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>
    <!-- <?php Pjax::end(); ?> -->
</div>

views/rpjm-indikator/create.php
<?php

use hscstudio\mimin\components\Mimin;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\RpjmIndikator */

$this->title = Yii::t('app', 'Create Rpjm Indikator');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Rpjm Indikators'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- <div class="rpjm-indikator-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div> -->
<?php Pjax::begin(); ?>
<p>
    <?= ((Mimin::checkRoute($this->context->id.'/index',true))) ? Html::a(Yii::t('app', 'Kembali'), ['index'], ['class' => 'btn btn-warning']) : null ?>
</p>
<div class="data-dasar-grid">

    <?= $this->render('_grid-data-dasar', [
            'searchModelDataDasar' => $searchModelDataDasar,
            'dataProviderDataDasar' => $dataProviderDataDasar,
        ]); ?>

</div>

<div class="data-dasar-detail">

    <?= $this->render('_detail-data-dasar', [
            'detailProviderDataDasar' => $detailProviderDataDasar,
        ]); ?>

</div>
<?php Pjax::end(); ?>